fail_fast: true
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff-check
        args: [--fix]
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args:
          - --no-strict-optional
          - --ignore-missing-imports
          - --no-incremental
          - --disable-error-code=override

  - repo: local
    hooks:
      - id: pytest
        name: run tests
        entry: pytest tests -vv
        language: system
        always_run: true
        pass_filenames: false
