name: build

on: [push]

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  pre-commit-and-test:
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7.0.7

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          architecture: x64
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install Dependencies
        run: |
          uv sync --locked --all-extras --dev

      - name: Run ruff linter
        shell: bash
        run: pre-commit run ruff-check --all-files

      - name: Run ruff formatter
        shell: bash
        run: pre-commit run ruff-format --all-files

      - name: Run mypy
        shell: bash
        run: pre-commit run mypy --all-files

      - name: Run pytest with code coverage
        run: |
          pytest --junitxml pytest.xml --cov=. --cov-report=term-missing --cov-report=xml:coverage.xml --cov-branch | tee pytest-coverage.txt
